blueprint:
  name: Awtrix Light Movement BluePrint
  description: Send a notification to Awtrix Light LED Clock when movement is detected
  domain: automation
  input:
    mqtt_prefix:
      name: MQTT Topic Prefix
      description: Message to display
      default: "awtrix"
    input_text:
      name: Message Text
      description: Message to display
      default: ""
    include_device_name:
      name: Show Device Name
      description: Include trigger device name in message
      selector:
        boolean:
      default: false
    icon:
      name: Icon ID
      description: Icon to display at beginning of message
      default: "47693"
    rainbow:
      name: Rainbow Colours
      description: Display message in rainbow colours
      selector:
        boolean:
      default: false
    hold:
      name: Hold Message
      description: Keep message displayed until button press
      selector:
        boolean:
      default: false
    duration:
      name: Duration (s)
      description: Time (seconds) to keep displaying the message
      selector:
        number:
          min: 1
          max: 60
      default: 5
    repeat:
      name: Repeat
      description: How many times to repeat the message
      selector:
        number:
          min: 1
          max: 10
      default: 1
    push_icon:
      name: Push Icon
      description: Icon should either be fixed position or scroll with text
      default: "0"
      selector:
        select:
          options:
            - label: Fixed
              value: "0"
            - label: Once
              value: "1"
            - label: Repeat
              value: "2"
          custom_value: false
          multiple: false
    text_color:
      name: Text colour
      description: The colour of the text
      selector:
        color_rgb:
      default: [255, 255, 255]
    background_color:
      name: Background colour
      description: The colour of the background
      selector:
        color_rgb:
      default: [0, 0, 0]
    sound:
      name: Sound file
      description: The filename of your RTTTL ringtone file (without extension)
      default: ""
    motion_entity:
      name: Movement Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - occupancy
            - motion
          multiple: true

mode: restart

variables:
  input_text: !input input_text
  icon: !input icon
  rainbow: !input rainbow
  hold: !input hold
  duration: !input duration
  push: !input push_icon
  text_color: !input text_color
  background_color: !input background_color
  repeat: !input repeat
  sound: !input sound
  mqtt_prefix: !input mqtt_prefix
  show_device_name: !input include_device_name
  message: >
    {% if show_device_name %}
      {{ trigger.from_state.attributes.friendly_name }} {{ input_text }}
    {% else %}
      {{ input_text }}
    {% endif %}

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

action:
  - service: mqtt.publish
    data:
      topic: "{{ mqtt_prefix }}/notify"
      payload: >
        {
          "text": "{{ message }}",
          "textCase": 2,
          "icon": "{{ icon }}",
          "rainbow": {{ rainbow | lower }},
          "hold": {{ hold | lower}},
          "pushIcon": {{ push | int }},
          "duration": {{ duration }},
          "color": {{ text_color }},
          "background": {{ background_color }},
          "repeat": {{ repeat }},
          "sound": {{ sound }}
        }
      qos: 0
      retain: false
